project_id = "rzhjotxffjfsdlhrdkpj"

[functions.create-user]
verify_jwt = false

[functions.analyze-brand]
verify_jwt = true

[functions.publish-scheduled-pages]
verify_jwt = false

[functions.migrate-page]
verify_jwt = true
