project_id = "rzhjotxffjfsdlhrdkpj"

[functions.create-user]
verify_jwt = false

[functions.analyze-brand]
verify_jwt = true

[functions.publish-scheduled-pages]
verify_jwt = false

[functions.migrate-page]
verify_jwt = true

[functions.process-image]
verify_jwt = true

[functions.chat-completion]
verify_jwt = false

[functions.get-page]
verify_jwt = false

[functions.invalidate-cache]
verify_jwt = true

[functions.content-api]
verify_jwt = false

[functions.generate-text]
verify_jwt = true
